In [1]:
from example_codes import bf_rep_code, qpc, steane_code, rsurf_code
from code_tools import commutation_test, order_set_list, max_elem
from cssCode import cssCode
import networkx as nx
import numpy as np

In [3]:
rsurf15_gens = rsurf_code(15)

In [4]:
rsurf15_css = cssCode(rsurf15_gens[0],rsurf15_gens[1])

In [5]:
rsurf15_ccgs = rsurf15_css.check_connectivity_graphs()

In [2]:
def Smatrix(n:int):
    Sm = np.zeros(shape = (n,n),dtype = int)
    for i in range(n):
        Sm[i,(i+1)%n] = 1
    return Sm

In [3]:
print(Smatrix(2))

[[0 1]
 [1 0]]


In [4]:
print(Smatrix(3))

[[0 1 0]
 [0 0 1]
 [1 0 0]]


In [5]:
print(Smatrix(7))

[[0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0]]


In [9]:
x = np.kron(Smatrix(2),np.eye(3,dtype=int))
y = np.kron(np.eye(2,dtype=int),Smatrix(3))

In [10]:
x

array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]])

In [11]:
y

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0]])

In [12]:
A = x**3+y+y**2
B = y**3+x+x**2

In [13]:
A

array([[0, 2, 0, 1, 0, 0],
       [0, 0, 2, 0, 1, 0],
       [2, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 2, 0],
       [0, 1, 0, 0, 0, 2],
       [0, 0, 1, 2, 0, 0]])

In [14]:
B

array([[0, 1, 0, 2, 0, 0],
       [0, 0, 1, 0, 2, 0],
       [1, 0, 0, 0, 0, 2],
       [2, 0, 0, 0, 1, 0],
       [0, 2, 0, 0, 0, 1],
       [0, 0, 2, 1, 0, 0]])

In [15]:
A = A%2

In [16]:
A

array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=int32)

In [17]:
B = B%2

In [18]:
B

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0]], dtype=int32)