In [2]:
import sys
import os
sys.path.append(os.path.abspath('..'))

In [3]:
# from codes.example_codes import *
# from codes.code_tools import pcm_to_sets,commutation_test
from csscode import cssCode
import networkx as nx
import numpy as np
from numpy import load

In [5]:
from codes.standard_surface_code_coordinates import surf_check_coords, surf_qubit_coords, potential_nbrhd

In [6]:
from codes.bivariate_bicycle_checks import Smatrix, xmatrix,ymatrix,Amatrix,Bmatrix,Smatrix,pcm

In [7]:
Adel = np.load('A.npy')
Abel = np.load('B.npy')

In [14]:
np.all(Adel==A)

True

In [13]:
np.all(Abel == B)

True

In [12]:
A[:,0]

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [10]:
hx,hz = pcm(12,6,[3,1,2],[3,1,2])

In [11]:
xgens = pcm_to_sets(hx)
zgens = pcm_to_sets(hz)

In [10]:
from codes.code_tools import commutation_test

In [13]:
bbc = cssCode(xgens,zgens)

In [11]:
A =Amatrix(12,6,3,1,2)
B = Bmatrix(12,6,3,1,2)
Hx = np.concatenate((A,B),axis=1)
Hz = np.concatenate((B.T,A.T),axis=1)

In [ ]:
for x in A:
    print(x)

In [11]:
print(A[0,:])

[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [12]:
print(A[:,0])

[0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [17]:
for i in range(len(A[:,0])):
    if A[i,0]:
        print(i)

4
5
54


In [15]:
A.shape

(36, 36)

In [14]:
len(bbc.qubits)

144

In [38]:
bbc.qubit_dict[0]

{False: {0, 1, 2}, True: {0, 1, 2}}

In [17]:
x_ccg = bbc.check_connectivity_graphs()[False]

Now consider paths connecting two different points

In [32]:
cycles0 = sorted(list(nx.cycle_basis(x_ccg,0)),key= lambda v: len(v))

In [34]:
path_set_lengths = []
for cxp in cycles0: ## check operators along the path
    print(cxp)
    path_set = set()
    for ii in range(len(cxp)):
        path_set = set.symmetric_difference(path_set,bbc.check_dict[False][cxp[ii]])
    path_set_lengths.append(len(path_set))

[30, 71, 0]
[43, 71, 0]
[51, 70, 71]
[69, 70, 71]
[48, 68, 70]
[67, 68, 70]
[49, 66, 68]
[65, 66, 68]
[63, 64, 66]
[69, 64, 66]
[61, 62, 64]
[67, 62, 64]
[59, 60, 62]
[65, 60, 62]
[57, 58, 60]
[63, 58, 60]
[55, 56, 58]
[61, 56, 58]
[3, 32, 56]
[14, 32, 56]
[50, 8, 32]
[63, 8, 32]
[7, 10, 8]
[13, 10, 8]
[28, 52, 10]
[34, 52, 10]
[1, 25, 52]
[5, 25, 52]
[42, 45, 25]
[47, 45, 25]
[9, 12, 10]
[15, 12, 10]
[3, 27, 56]
[9, 27, 56]
[38, 14, 56]
[57, 55, 58]
[5, 34, 58]
[16, 34, 58]
[5, 29, 58]
[11, 29, 58]
[40, 16, 58]
[59, 57, 60]
[7, 36, 60]
[18, 36, 60]
[7, 31, 60]
[13, 31, 60]
[42, 18, 60]
[61, 59, 62]
[9, 38, 62]
[20, 38, 62]
[9, 33, 62]
[15, 33, 62]
[63, 61, 64]
[11, 40, 64]
[22, 40, 64]
[11, 35, 64]
[17, 35, 64]
[65, 63, 66]
[13, 42, 66]
[23, 42, 66]
[13, 37, 66]
[19, 37, 66]
[47, 23, 66]
[67, 65, 68]
[2, 44, 68]
[15, 44, 68]
[15, 39, 68]
[21, 39, 68]
[2, 26, 68]
[21, 26, 68]
[51, 48, 70]
[4, 46, 70]
[17, 46, 70]
[1, 41, 70]
[17, 41, 70]
[1, 28, 70]
[4, 28, 70]
[49, 69, 71]
[50, 53, 71

In [35]:
len(path_set_lengths)

361

In [36]:
max(path_set_lengths)

64

In [37]:
min(path_set_lengths)

12

In [23]:
np.average(path_set_lengths)

27.53999332929797

In [31]:
vdegs = [len(list(x_ccg.neighbors(v))) for v in x_ccg.nodes]

If the redundancies aren't showing up in cycles, then we should check larger objects.
Maybe cliques

In [9]:
clicks = list(nx.find_cliques(x_ccg,[0]))

In [10]:
clicks[0]

[0, 1, 8]

In [11]:
for cl in clicks:
    print(cl)

[0, 1, 8]
[0, 1, 2]
[0, 3, 10]
[0, 3, 4]
[0, 4, 2]
[0, 35, 18]
[0, 35, 19]
[0, 10, 8]
[0, 12, 30]
[0, 12, 31]
[0, 18, 30]
[0, 19, 31]


Looks like there are two sets of cycles that all multiply to the identity:

[0, 1, 8]
[0, 1, 2]
[0, 4, 2]
[0, 3, 10]
[0, 3, 4]
[0, 10, 8]

[0, 35, 18]
[0, 35, 19]
[0, 12, 30]
[0, 12, 31]
[0, 18, 30]
[0, 19, 31]

But does this mean anything?

In [14]:
supp0 = bbc.check_dict[False][0]
supp1 = bbc.check_dict[False][1]
supp8 = bbc.check_dict[False][8]

In [15]:
for sup in [supp0,supp1,supp8]:
    print(sup)

{0, 1, 38, 47, 53, 23}
{0, 37, 5, 46, 52, 22}
{3, 69, 23, 54, 22, 63}


In [22]:
print([supp0&supp1,supp0&supp8,supp1&supp8])

[{0}, {23}, {22}]


In [23]:
ccg = bbc.check_chain_graph()

In [32]:
x0zn = set(ccg.neighbors((False,0)))
x1zn = set(ccg.neighbors((False,1)))
x8zn = set(ccg.neighbors((False,8)))

print(list(x0zn))
print(list(x1zn))
print(list(x8zn))

[(True, 2), (True, 5), (True, 1), (True, 20), (True, 4), (True, 0), (True, 29), (True, 35), (True, 3)]
[(True, 28), (True, 2), (True, 15), (True, 34), (True, 1), (True, 17), (True, 16), (True, 0), (True, 19)]
[(True, 28), (True, 11), (True, 34), (True, 20), (True, 10), (True, 29), (True, 35), (True, 19), (True, 9)]


In [34]:
print(list(x0zn&x1zn))
print(list(x0zn&x8zn))
print(list(x1zn&x8zn))

[(True, 0), (True, 1), (True, 2)]
[(True, 29), (True, 35), (True, 20)]
[(True, 28), (True, 19), (True, 34)]


In [37]:
print(bbc.check_dict[True][0])
print()
print(bbc.check_dict[False][0])
print(bbc.check_dict[False][1])

{0, 66, 6, 15, 52, 53}

{0, 1, 38, 47, 53, 23}
{0, 37, 5, 46, 52, 22}


In [44]:
print(bbc.check_dict[True][19])
print()
print(bbc.check_dict[False][1])
print(bbc.check_dict[False][8])

{37, 7, 13, 54, 22, 59}

{0, 37, 5, 46, 52, 22}
{3, 69, 23, 54, 22, 63}


In [43]:
bbc.qubit_dict[22]

{False: {1, 6, 8}, True: {19, 28, 34}}

In [12]:
click_sets = []
for ii in range(len(clicks)): ## check operators along the path
    click_set = set()
    for jj in range(len(clicks[ii])):
        click_set = set.symmetric_difference(click_set,bbc.check_dict[False][clicks[ii][jj]]&bbc.check_dict[False][clicks[ii][(jj+1)%len(clicks[ii])]])
    click_sets.append(click_set)

In [52]:
ccg = bbc.check_chain_graph()

In [58]:
scs = nx.simple_cycles(ccg,length_bound=6)

In [59]:
list(scs)[0]

[(False, 0), (True, 0), (False, 1), (True, 1)]