Here is a demonstration of how to use the tools in this repo to construct syndrome extraction circuits for the rotated surface code and to evaluate a threshold for logical state preparation under a simple single-qubit error model.

In [18]:
import sys
import os
sys.path.append(os.path.abspath('..'))

In [19]:
import pymatching
import numpy as np

from scipy import sparse
from stim import Circuit
from csscode.cssCode import cssCode

from codes.code_tools import commutation_test
from codes.rotated_surface_code_coordinates import rsurf_stabilizer_generators as stabgens

Functions for initializing the rotated surface code data:

In [23]:
def rsurf_code(L:int):
    sx,sz = stabgens(L,L)
    return cssCode(sx,sz)

def zlogical(L:int):
    rsc = rsurf_code(L)
    return rsc.zlogicals[0]

In [24]:
zlogical(5)

{0, 1, 2, 3, 4}

Test that the $X$-generators of the code commute with the logical-$Z$ operator using the commutation_test function:

In [25]:
for L in [7,11,15]:
    print(commutation_test([zlogical(L)],stabgens(L,L)[0]))

True
True
True


Circuits for syndrome extraction and logical Z measurements of the rotated surface code:

In [26]:
def z_syn_circ(circuit:Circuit,code:cssCode):
    for zcheck in code.check_dict[True]:
        anc_qub = code.Nqubits+zcheck
        for dat_qub in code.check_dict[True][zcheck]:
            circuit.append("CX",[dat_qub,anc_qub])
        circuit.append("MR",anc_qub)

def x_syn_circ(circuit:Circuit,code:cssCode):
    for xcheck in code.check_dict[False]:
        anc_qub = code.Nqubits+len(code.check_dict[True])+xcheck
        circuit.append("H",anc_qub)
        for dat_qub in code.check_dict[False][xcheck]:
            circuit.append("CX",[anc_qub,dat_qub])
        circuit.append("H",anc_qub)
        circuit.append("MR",anc_qub)

def zL_meas_circ(circuit:Circuit,code:cssCode):
    L = int(np.sqrt(code.Nqubits)) ## Only intended for rotated surface code
    zL_qub = code.Nqubits+len(code.check_dict[True])+len(code.check_dict[False])
    for dat_qub in zlogical(L):
        circuit.append("CX",[dat_qub,zL_qub])
    circuit.append("MR",zL_qub)

In [27]:
def apply_single_qubit_noise(circuit:Circuit,code:cssCode,p:list[float]):
    circuit.append("PAULI_CHANNEL_1",list(code.qubits),[p[0],p[1],p[2]])

#### Code capacity experiment
One round of single-qubit noise, followed by perfect syndrome extraction and then a logical measurement.

In [28]:
rs3 = rsurf_code(3)

circ = Circuit()
apply_single_qubit_noise(circ,rs3,[0.1,0.0,0.1])
z_syn_circ(circ,rs3)
x_syn_circ(circ,rs3)
zL_meas_circ(circ,rs3)
circ.diagram()

q0: -PAULI_CHANNEL_1(0.1,0,0.1)-@---------------------------------------------------------------X-----------------------------------------------------------------------@---------------
                                 |                                                               |                                                                       |
 q1: -PAULI_CHANNEL_1(0.1,0,0.1)-|-@-------------------------------------------------------------|-X-------------X-------------------------------------------------------|-@-------------
                                 | |                                                             | |             |                                                       | |
 q2: -PAULI_CHANNEL_1(0.1,0,0.1)-|-|---------------@---------------------------------------------|-|-------------|-X-----------------------------------------------------|-|-@-----------
                                 | |               |                                             | |             | |                                                     | | |
 q3: -PAULI_CHANNEL_1(0.1,0,0.1)-|-|-@-------------|-------------@-------------------------------|-|-------------|-|-----------------X-----------------------------------|-|-|-----------
                                 | | |             |             |                               | |             | |                 |                                   | | |
 q4: -PAULI_CHANNEL_1(0.1,0,0.1)-|-|-|-@-----------|-------------|---------------@---------------|-|-------------|-|-X---------------|-X---------------------------------|-|-|-----------
                                 | | | |           |             |               |               | |             | | |               | |                                 | | |
 q5: -PAULI_CHANNEL_1(0.1,0,0.1)-|-|-|-|-----------|-@-----------|---------------|-@-------------|-|-------------|-|-|-X-------------|-|---------------------------------|-|-|-----------
                                 | | | |           | |           |               | |             | |             | | | |             | |                                 | | |
 q6: -PAULI_CHANNEL_1(0.1,0,0.1)-|-|-|-|-----------|-|-----------|-@-------------|-|-------------|-|-------------|-|-|-|-------------|-|-X-------------------------------|-|-|-----------
                                 | | | |           | |           | |             | |             | |             | | | |             | | |                               | | |
 q7: -PAULI_CHANNEL_1(0.1,0,0.1)-|-|-|-|-----------|-|-----------|-|-------------|-|-@-----------|-|-------------|-|-|-|-------------|-|-|-X---------------X-------------|-|-|-----------
                                 | | | |           | |           | |             | | |           | |             | | | |             | | | |               |             | | |
 q8: -PAULI_CHANNEL_1(0.1,0,0.1)-|-|-|-|-----------|-|-----------|-|-----------@-|-|-|-----------|-|-------------|-|-|-|-------------|-|-|-|-------------X-|-------------|-|-|-----------
                                 | | | |           | |           | |           | | | |           | |             | | | |             | | | |             | |             | | |
 q9: ----------------------------X-X-X-X-MR:rec[0]-|-|-----------|-|-----------|-|-|-|-----------|-|-------------|-|-|-|-------------|-|-|-|-------------|-|-------------|-|-|-----------
                                                   | |           | |           | | | |           | |             | | | |             | | | |             | |             | | |
q10: ----------------------------------------------X-X-MR:rec[1]-|-|-----------|-|-|-|-----------|-|-------------|-|-|-|-------------|-|-|-|-------------|-|-------------|-|-|-----------
                                                                 | |           | | | |           | |             | | | |             | | | |             | |             | | |
q11: -------------------------------

Parity check matrices for the rotated surface code:

In [29]:
zpcm = rs3.to_check_matrices()[True]
zrow = [elem[0] for elem in zpcm]
zcol = [elem[1] for elem in zpcm]
zdata = [elem[2] for elem in zpcm]

hz = sparse.coo_array((zdata,(zrow,zcol))).toarray()

xpcm = rs3.to_check_matrices()[False]
xrow = [elem[0] for elem in xpcm]
xcol = [elem[1] for elem in xpcm]
xdata = [elem[2] for elem in xpcm]

hx = sparse.coo_array((xdata,(xrow,xcol))).toarray()

print('hz = ' +'\n'+str(hz))
print()
print('hx = ' +'\n'+str(hx))

hz = 
[[1 1 0 1 1 0 0 0 0]
 [0 0 1 0 0 1 0 0 0]
 [0 0 0 1 0 0 1 0 0]
 [0 0 0 0 1 1 0 1 1]]

hx = 
[[1 1 0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0 0 0]
 [0 0 0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0 1 1]]


In [16]:
num_shots = 10000

py = 0
pz = 0

for px in [0.07, 0.10, 0.13]:

    print('px = ' + str(px))

    for L in [11,15,19,23]:
        num_errs = 0
        rs = rsurf_code(L)

        zpcm = rs.to_check_matrices()[True]
        zrow = [elem[0] for elem in zpcm]
        zcol = [elem[1] for elem in zpcm]
        zdata = [elem[2] for elem in zpcm]

        hz = sparse.coo_array((zdata,(zrow,zcol))).toarray()
        zL = np.array([1]*L+[0]*(rs.Nqubits-L),dtype = int)

        matching = pymatching.Matching(hz)

        ## Initialize the state (all qubits initially in |0> state)
        ## Apply single qubit noise
        ## Perform syndrome extraction
        ## Measure the logical-Z operator

        circ = Circuit()
        apply_single_qubit_noise(circ,rs,[px,py,pz])
        z_syn_circ(circ,rs)
        x_syn_circ(circ,rs)
        zL_meas_circ(circ,rs)


        ## Generate a sampler of the circuit then perform num_shots trials
        sampler = circ.compile_sampler()
        results = sampler.sample(shots=num_shots)

        ## Assess each result for a logical failure
        for res in results:

            ## Extract the Z portion of the syndrome (the first measurement outcomes from each trial)
            ## Also extract the observed value of the logical-Z operator (the last measurement outcome from each trial)
            zsynd = res[:len(rs.code[True])]
            zmeas = res[-1]

            ## Obtain the predicted error from the decoder for the observed Z-syndrome
            prediction = matching.decode(zsynd)

            ## Perform error-recovery by modifying the observed logical-Z output
            ## The dot product of the Z-logical operator and the predicted X-error tells us if we need to flip zmeas
            ## The initial value of zL is |0>, so if the correction predicts |1>, then error has occurred
            num_errs += (zmeas + zL@prediction.T)%2

        print('L = ' + str(L) + ', num errs = ' + str(num_errs))
    
    print()


px = 0.07
L = 11, num errs = 315
L = 15, num errs = 236
L = 19, num errs = 165
L = 23, num errs = 114

px = 0.1
L = 11, num errs = 1259
L = 15, num errs = 1322
L = 19, num errs = 1305
L = 23, num errs = 1365

px = 0.13
L = 11, num errs = 2589
L = 15, num errs = 2971
L = 19, num errs = 3189
L = 23, num errs = 3401



### Phenomenological Pauli-$X$, -$Z$ noise model

We apply independent Pauli-$X$ and -$Z$ noise with equal probability.
The syndrome extraction circuits are perfect, but with a probability $p_{meas}$ of flipping the reported outcome of measurements.

In [30]:
def phenom_z_syn_circ(circuit:Circuit,code:cssCode,pmeas:float):
    for zcheck in code.check_dict[True]:
        anc_qub = code.Nqubits+zcheck
        
        for dat_qub in code.check_dict[True][zcheck]:
            circuit.append("CX",[dat_qub,anc_qub])
        
        circuit.append("X_ERROR",anc_qub,pmeas)
        circuit.append("MR",anc_qub)

def phenom_x_syn_circ(circuit:Circuit,code:cssCode,pmeas:float):
    for xcheck in code.check_dict[False]:
        anc_qub = code.Nqubits+len(code.check_dict[True])+xcheck

        circuit.append("H",anc_qub)

        for dat_qub in code.check_dict[False][xcheck]:
            circuit.append("CX",[anc_qub,dat_qub])

        circuit.append("H",anc_qub)
        circuit.append("X_ERROR",anc_qub,pmeas)        
        circuit.append("MR",anc_qub)

def phenom_syndrome_circuit(L:int,p1:float,pmeas:float):

    rs = rsurf_code(L)
    circ = Circuit()
    for round in range(L):
        apply_single_qubit_noise(circ,rs,[p1,0,0])
        apply_single_qubit_noise(circ,rs,[0,0,p1])
        phenom_z_syn_circ(circ,rs,pmeas)
        phenom_x_syn_circ(circ,rs,pmeas)
    zL_meas_circ(circ,rs)

    return circ

In [31]:
circ = phenom_syndrome_circuit(3,.001,.001)
circ.diagram()

q0: -PAULI_CHANNEL_1(0.001,0,0)-PAULI_CHANNEL_1(0,0,0.001)-@---------------------------------------------------------------------------------------------------------------------------X-------------------------------------------------------------------------------------------------------------------------PAULI_CHANNEL_1(0.001,0,0)-PAULI_CHANNEL_1(0,0,0.001)-@-----------------------------------------------------------------------------------------------------------------------------X----------------------------------------------------------------------------------------------------------------------------PAULI_CHANNEL_1(0.001,0,0)-PAULI_CHANNEL_1(0,0,0.001)-@-------------------------------------------------------------------------------------------------------------------------------X---------------------------------------------------------------------------------------------------------------------------------------@----------------
                                                            |                                                                                                                           |                                                                                                                                                                               |                                                                                                                             |                                                                                                                                                                                  |                                                                                                                               |                                                                                                                                       |
 q1: -PAULI_CHANNEL_1(0.001,0,0)-PAULI_CHANNEL_1(0,0,0.001)-|-@-------------------------------------------------------------------------------------------------------------------------|-X----------------------------X------------------------------------------------------------------------------------------PAULI_CHANNEL_1(0.001,0,0)-PAULI_CHANNEL_1(0,0,0.001)-|-@---------------------------------------------------------------------------------------------------------------------------|-X-----------------------------X--------------------------------------------------------------------------------------------PAULI_CHANNEL_1(0.001,0,0)-PAULI_CHANNEL_1(0,0,0.001)-|-@-----------------------------------------------------------------------------------------------------------------------------|-X-----------------------------X-------------------------------------------------------------------------------------------------------|-@--------------
                                                            | |                                                                                                                         | |                            |                                                                                                                                                | |                                                                                                                           | |                             |                                                                                                                                                  | |                                                                                                                             | |                             |                                                                                                       | |
 q2: -PAULI_CHANNEL_1(0.001,0,0)-PAULI_CHANNEL_1(0,0,0.001)-|-|------------------------------@------------------------------------------------------------------------------------------|-|----------------------------|-X-------------------------

We can now sample the circuit to establish an error threshold for the identity operation of the rotated surface code.

In [ ]:
num_shots = 2000
num_errs = 0

for px in [0.0005, 0.001, 0.0015]:

    print('px = ' + str(px))

    for L in [11,15,19,23]:
        num_errs = 0
        rs = rsurf_code(L)

        zpcm = rs.to_check_matrices()[True]
        zrow = [elem[0] for elem in zpcm]
        zcol = [elem[1] for elem in zpcm]
        zdata = [elem[2] for elem in zpcm]

        hz = sparse.coo_array((zdata,(zrow,zcol))).toarray()
        zlog = rs.zlogicals[0]
        zL = np.array([int(ii in zlog) for ii in range(rs.Nqubits)])

        matching = pymatching.Matching(hz)

        ## Initialize the state (all qubits initially in |0> state)
        ## Apply single qubit noise
        ## Perform syndrome extraction
        ## Measure the logical-Z operator

        circ = phenom_syndrome_circuit(L,px,px)

        ## Generate a sampler of the circuit then perform num_shots trials
        sampler = circ.compile_sampler()
        results = sampler.sample(shots=num_shots)

        ## Assess each result for a logical failure
        for res in results:

            ## Need to generate matching object for repeated measurements.

            pass

        print('L = ' + str(L) + ', num errs = ' + str(num_errs))
    
    print()

px = 0.0005
L = 11, num errs = 131
L = 15, num errs = 243
L = 19, num errs = 336
L = 23, num errs = 461

px = 0.001
L = 11, num errs = 237
L = 15, num errs = 410
L = 19, num errs = 560
L = 23, num errs = 730

px = 0.0015
L = 11, num errs = 337
L = 15, num errs = 538
L = 19, num errs = 716
L = 23, num errs = 837



Below are the noisy versions of the above syndrome measurement circuits, where the model is single-qubit and two-qubit depolarizing noise with error probabilities of $p1$ and $p2$, respectively.

In each circuit noisy state preparation and measurement is modeled with single-qubit depolarizing noise following preparation, or preceding measurement, respectively.

Each noisy two-qubit gate is modeled as the ideal gate followed by a two-qubit depolarizing channel.

In [ ]:
def noisy_z_syn_circ(circuit:Circuit,code:cssCode,p1:float,p2:float):
    for zcheck in code.check_dict[True]:
        anc_qub = code.Nqubits+zcheck
        
        circuit.append("DEPOLARIZE1",anc_qub,p1)
        
        for dat_qub in code.check_dict[True][zcheck]:
            circuit.append("CX",[dat_qub,anc_qub])
            circuit.append("DEPOLARIZE2",[dat_qub,anc_qub],p2)
        
        circuit.append("DEPOLARIZE1",anc_qub,p1)
        circuit.append("MR",anc_qub)

def noisy_x_syn_circ(circuit:Circuit,code:cssCode,p1:float,p2:float):
    for xcheck in code.check_dict[False]:
        anc_qub = code.Nqubits+len(code.check_dict[True])+xcheck

        circuit.append("H",anc_qub)
        circuit.append("DEPOLARIZE1",anc_qub,p1)

        for dat_qub in code.check_dict[False][xcheck]:
            circuit.append("CX",[anc_qub,dat_qub])
            circuit.append("DEPOLARIZE2",[anc_qub,dat_qub],p2)
        
        circuit.append("H",anc_qub)
        circuit.append("MR",anc_qub)

def noisy_syndrome_circuit(L:int,p1,p2):

    rs = rsurf_code(L)
    circ = Circuit()
    for round in range(L):
        apply_single_qubit_noise(circ,rs,[p1,p1,p1])
        noisy_z_syn_circ(circ,rs,p1,p2)
        noisy_x_syn_circ(circ,rs,p1,p2)
    zL_meas_circ(circ,rs)

    return circ

Below we'll run a numerical experiment to estimate the threshold for the toric code under this noise model.
In particular, we will:
1. Prepare a state in a simultaneous $\bar{X}_A \bar{X}_B$, $\bar{Z}_A \bar{Z}_B$ eigenstate of the $L \times L$ toric code
2. Perform $L$ rounds of noisy syndrome extraction
3. Decode both the $X$ and $Z$ check systems
4. Readout the $\bar{X}_A \bar{X}_B$, $\bar{Z}_A \bar{Z}_B$ eigenvalues (with a noiseless circuit)
5. Compare the decoded output eigenvalues with the initialized eigenvalues to see if a logical error has occurred.